### ISSUE TITLE
security at project compiling

### ISSUE THREAD

**Issue by PedroCarrillo** [belatrix/AndroidAllStars#11]
@gyosida, @cpinan 

What do you think of improving our server base url protection? We can put the base on gradle file and pull them from a local.properties?

Although our endpoint applies authentication methods, we still are vulnerable to attacks.

**Comment by cpinan** [comment]
I think is ok use an external properties. Maybe not the local but a custom one.

**Comment by gyosida** [comment]
Sounds good
