### ISSUE TITLE
Cannot resize the picture with pictures from the gallery

### ISSUE THREAD

**Issue by joyep-jojo** [belatrix/AndroidAllStars#128]

**Comment by PedroCarrillo** [comment]
this is because i set a minimum size. if an image of a cellphone is 3200x1500 it will allow you pick a little part of it until 300x300 while an image of 320x480 wont have much space to resize

**Comment by PedroCarrillo** [comment]
if we don't set a minimum you can pick a very little image which would look very bad.

**Comment by gyosida** [comment]
do not proceed, closing it
