### ISSUE TITLE
Logout: Session Management

### ISSUE THREAD

**Issue by mmanna** [belatrix/AndroidAllStars#157]
Currently there isn´t a session management. It should be useful have it for security.

**Comment by gyosida** [comment]
can you explain us what you mean by "session management"?

**Comment by gyosida** [comment]
@neosergio, up to what @mmanna told me, is about having the token to expire.
So, it will demand some changes in both ends, since client would have to receive, perhaps in the Authentication response, how long the token will live. Let me know any thoughts, please.

**Comment by PedroCarrillo** [comment]
@neosergio ping
