### ISSUE TITLE
Navigation tab and user profile 

### ISSUE THREAD

**Issue by claucastv** [belatrix/AndroidAllStars#176]
When we are in the ranking screen and one of the employees user profile image is in the middle of the navigation bar and we select 'Last Month ' tab.
The screen gets freezer and goes to the profile user.
![screenshot_20160719-142152-1](https://cloud.githubusercontent.com/assets/16712559/16964430/071bb9fa-4dc1-11e6-890b-0f0e1f3ec882.png)
![screenshot_20160719-142250](https://cloud.githubusercontent.com/assets/16712559/16964436/09d4a6ca-4dc1-11e6-9711-735e12c91a44.png)

**Comment by PedroCarrillo** [comment]
there is a reason why @gyosida did it this way. If there is no choice we should keep it this way, although i haven't seen any other app have this behaviour

**Comment by EduardoChuks** [comment]
this is a bug by default from google's api, we would need to make a custom animation and change it in the whole app to solve this.
