### ISSUE TITLE
Navigation its incorrect

### ISSUE THREAD

**Issue by claucastv** [belatrix/AndroidAllStars#177]
When the user select a profile of an employee from the ranking list and tap on the back button the user returns to their own profile view.

Expected:
The user should return to the ranking list
Actual:
The user return to their own profile

**Comment by PedroCarrillo** [comment]
@icerrate, we need to check the lifecycle, maybe we are setting the fragment on the onResume?

**Comment by EduardoChuks** [comment]
Navigation fixed
