### ISSUE TITLE
Delay on Profile Image loading only first loading

### ISSUE THREAD

**Issue by fpuebla** [belatrix/AndroidAllStars#234]
Steps:

1. login into the app at first time
2. Tap Contact section
3. Select any contact
4. Into Profile Page tap image profile

Expected:

- Profile Image should be loaded immediately

Actual:

- Delay on Profile Image loading only first loading

Test on:
|Motorola G4 Plus (Android 7)|
|Samsung S4 (Android 4.4.2)|

**Comment by guillermo20** [comment]
@fpuebla isn't that the normal behavior? when caching the images for the first time it will be a little bit slow because it has to transfer the image's data from the server.

**Comment by fpuebla** [comment]
It seems this behavior is not happening anymore on the last app version.
