### ISSUE TITLE
Add warning message on tap back to prevent exit app

### ISSUE THREAD

**Issue by fpuebla** [belatrix/AndroidAllStars#249]
App exit when user tap on the back button on Setting, Profile, Events, Contacts and Ranking Sections.
The App should prevent to exit by a warning message.

**Comment by guillermo20** [comment]
@diegoveloper isn't this issue against one of the core quality guidelines?

> The app supports standard system Back button navigation and does not make use of any custom, on-screen "Back button" prompts.


> The app does not redefine the expected function of a system icon (such as the Back button).

https://developer.android.com/develop/quality-guidelines/core-app-quality.html

**Comment by diegoveloper** [comment]
@guillermo20 You could use this dialog as example : https://i.stack.imgur.com/gZrvl.png

**Comment by fpuebla** [comment]
there is a defect due to this enhancement: the message added is displayed in wrong pages. E.g.: Edit profile, go back. Defect created: #260
