### ISSUE TITLE
Add 'previous view' to show pass on the Login screen

### ISSUE THREAD

**Issue by fpuebla** [belatrix/AndroidAllStars#250]
Sometimes the user needs to see if him/her entered a correct password.
The system should add a 'previous view' to show the pass on the login screen.

**Comment by guillermo20** [comment]
@diegoveloper i don't understand how this "previous view" works or where it needs to be implemented

**Comment by fpuebla** [comment]
Hi @guillermo20 is about to add a 'hide/show password' option into the password field. 
This is a sample:
![image](https://user-images.githubusercontent.com/27304405/26947876-ae02cd5a-4c6a-11e7-8479-b63f1d325b8f.png)

**Comment by guillermo20** [comment]
@fpuebla @diegoveloper clarified!

**Comment by diegoveloper** [comment]
@guillermo20 You can use a [TextInputLayout](https://developer.android.com/reference/android/support/design/widget/TextInputLayout.html) component with the password toggle enabled.

**Comment by fpuebla** [comment]
Verified fixed.
